### ISSUE TITLE
Antibiotic resistance

### ISSUE THREAD

**Issue by jacakrj1** [jhuapl-bio/pathogenesis-gene-ontology#184]
Propose adding the term "mediates resistance to antibiotics" to the ontology, as a single term that cross references the CARD ontology as well as GO term 'GO:0046677 - response to antibiotic'.  As Amanda pointed out after the last annotation session, penicillins are synthesized by fungi for host defense purposes, and we currently have "PATHGO:0000104 - disrupts antimicrobial peptide binding" in the ontology.   So, this new term could live under "PATHGO:0000085 - mediates immune evasion and subversion", but we think it may better fit under "PATHGO:0000150 - mediates proliferation and survival" since it satisfies the requirement of that term "A mechanism that mediates pathogenicity by allowing pathogens to grow and multiply, especially when environmental conditions are unfavorable, distinct from adherence and colonization."  Thoughts?

**Comment by genegodbold** [comment]
Not just fungi--bacteria use them against other bacteria. Antibiotic inactivation enzymes are present in the bacteria that make these antibiotics so as not to, you know, commit suicide in the process. 
:-)
I agree with you guys that since CARD exists, it isn't necessary to duplicate its effort; a single term that captures the myriad ways of enabling antibiotic resistance is fine. From my way of thinking, antibiotic resistance is just NOT that threatening compared to things that actually *damage* a host or actively (or even passively) subvert the immune system. But it IS something to note.

**Comment by jacakrj1** [comment]
Jody merged a PR for this in last week, so closing this one out.
