### ISSUE TITLE
Move 'mediates nutrient availability terms' under 'direct mechanism of pathogenicity' branch

### ISSUE THREAD

**Issue by jacakrj1** [jhuapl-bio/pathogenesis-gene-ontology#204]
All of the terms under 'mediates nutrient availability or uptake', like for example 'mediates DNA cleavage', seem like they would be directly pathogenic.  Should find a place under 'direct mechanism of pathogenicity' for them.

**Comment by genegodbold** [comment]
It is not true that all these things would be directly pathogenic. For instance, despite everybody and his brother declaring that hyaluronidase is a virulence factor (it degrades hyaluronan/hyaluronic acid), I have never seen any direct evidence in any microbe that it contributes to host damage. It is all suggestive or circumstantial. Instead, it is more likely to be part of nutrient availability. (I welcome citations that would indicate the contrary for particular organisms. I've been chasing down these things for years.)

**Comment by jproesch** [comment]
Maybe a better approach is to remove terms that we don't have examples/references for as being a relevant/valid damaging mechanism...i.e., is 'mediates DNA cleavage' something that has been documented as a nutrient availability mechanism? Are the others?

**Comment by genegodbold** [comment]
@jproesch I don't have any examples of mediating DNA cleavage as something that affects nutrient availability, but  that is because I don't care about nutrient availability as I have not considered it to be relevant to pathogenesis or host damage (in as much as they might be thought to differ). However, there are DNases that are used by bacteria to cut neutrophil extracellular traps (NETs) and I have noted those. Their could, perhaps, be a "mediating host DNA cleavage" term, but that does seem too generic and prone to all sorts of mis-use.

**Comment by jproesch** [comment]
@genegodbold thanks.  'mediates DNA cleavage' does not seem to add value, and the same is likely true for the protein degradation and carbohydrate degradation terms as well.

**Comment by genegodbold** [comment]
@jproesch Now there are cyclomodulins that "mediate host DNA cleavage". That would be a reason for retaining this term. They also tend to mess with the host cell cycle. This would include things like cytolethal distending toxin (CDT) which is found in a variety of enteric bacteria. There are also other pathogenic sequences with nuclease activity like MGA-0676 from Mycoplasma gallisepticum, pneumolysin from S. pneumonia, Mycoplasma pneumoniae nuclease 133, EssD from S. aureus, Endonuclease A from Streptococcus. I could go on. I think there are annotation reasons to have the term "mediates host DNA cleavage" OR "mediates cleavage of DNA in host cell" (which would be a little broader). What I'm saying is I can use this on existing terms if you can find a reasonable place in the ontology to put it.

**Comment by jacakrj1** [comment]
Agree with you on this one, @genegodbold.  I'm pretty sure there was a specific example where the term 'mediates DNA cleavage' was added.  And yes, agree we should disambiguate it by using 'mediates host DNA cleavage'.  Should also note that the case I'm thinking about I'm pretty sure was more about the bug cleaving the DNA to disrupt normal cell operations, as opposed to just doing it for nutrient availability, but I suppose the two go hand in hand.  Will reopen this issue.

**Comment by genegodbold** [comment]
@jproesch @rjacak To be clear, I do NOT think it should be a child under a "nutrient availability" term. Because in the cases I mention above, I don't think the parasite is doing it for "nutrition" at all. It would be more appropriate (I think) as a child of either PATHGO_0000166 (disrupts cellular structure) OR PATHGO_0000164 (disrupts cellular metabolism).

**Comment by jacakrj1** [comment]
My first thought was the same, but we already have some terms related to DNA synthesis inhibition under metabolism, so it felt more appropriate to put it under 'disrupts cellular metabolism'.  Can always move it later if we feel it's misplaced.

**Comment by jacakrj1** [comment]
Merged in PR #237

**Comment by genegodbold** [comment]
@rjacak That will work, thanks!
